# Generated by Django 6.0.4 on 2026-05-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'userlist',
                'managed': False,
            },
        ),
    ]
